export const STORAGE_KEY='chell-freemium-v1';
export const JSON_EXPORT_BUNDLE_SIZE=4; export const JSON_EXPORT_BUNDLE_PRICE_EUR=3; export const JSON_EXPORT_FREE_LIMIT=3; export const RECORDING_DOWNLOAD_PRICE_EUR=9.99;
export interface CommerceState{freeJsonRemaining:number;paidJsonCredits:number;recordingDownloadUnlocked:boolean;simulatedRevenue:number;purchaseHistory:Array<{kind:'json_bundle'|'recording_unlock';amount:number;createdAt:string;}>;}
export const defaultCommerceState=():CommerceState=>({freeJsonRemaining:JSON_EXPORT_FREE_LIMIT,paidJsonCredits:0,recordingDownloadUnlocked:false,simulatedRevenue:0,purchaseHistory:[]});
export function loadCommerceState():CommerceState{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return defaultCommerceState();const parsed=JSON.parse(raw) as Partial<CommerceState>;return {...defaultCommerceState(),...parsed,purchaseHistory:parsed.purchaseHistory??[]};}catch{return defaultCommerceState();}}
export function saveCommerceState(state:CommerceState){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
export function consumeJsonExport(state:CommerceState):CommerceState{if(state.freeJsonRemaining>0)return {...state,freeJsonRemaining:state.freeJsonRemaining-1}; if(state.paidJsonCredits>0)return {...state,paidJsonCredits:state.paidJsonCredits-1}; throw new Error('No JSON export credits available.');}
export function grantJsonBundle(state:CommerceState):CommerceState{return {...state,paidJsonCredits:state.paidJsonCredits+JSON_EXPORT_BUNDLE_SIZE,simulatedRevenue:Number((state.simulatedRevenue+JSON_EXPORT_BUNDLE_PRICE_EUR).toFixed(2)),purchaseHistory:[{kind:'json_bundle',amount:JSON_EXPORT_BUNDLE_PRICE_EUR,createdAt:new Date().toISOString()},...state.purchaseHistory]};}
export function unlockRecordingDownload(state:CommerceState):CommerceState{return {...state,recordingDownloadUnlocked:true,simulatedRevenue:Number((state.simulatedRevenue+RECORDING_DOWNLOAD_PRICE_EUR).toFixed(2)),purchaseHistory:[{kind:'recording_unlock',amount:RECORDING_DOWNLOAD_PRICE_EUR,createdAt:new Date().toISOString()},...state.purchaseHistory]};}
